# Generated by Django 5.2 on 2025-08-02 08:57

import django.core.validators
import django.db.models.deletion
import sorl.thumbnail.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Дата создания."),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Дата обновления."),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Логическое удаление."
                    ),
                ),
                (
                    "reg_number",
                    models.CharField(
                        help_text="Регистрационный номер.", max_length=255
                    ),
                ),
                ("brand", models.CharField(help_text="Марка.", max_length=255)),
                ("date_purchase", models.DateField(help_text="Дата покупки.")),
                (
                    "mileage",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Пробег.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.000"))
                        ],
                    ),
                ),
                (
                    "operation_status",
                    models.CharField(
                        choices=[
                            ("in_work", "В работе"),
                            ("unuse", "Простой"),
                            ("repair", "Ремонт"),
                        ],
                        max_length=7,
                    ),
                ),
            ],
            options={
                "verbose_name": "Техника",
                "verbose_name_plural": "Техника",
            },
        ),
        migrations.CreateModel(
            name="VehicleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Дата создания."),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Дата обновления."),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Логическое удаление."
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название типа.", max_length=255, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип техники",
                "verbose_name_plural": "Типы техники",
            },
        ),
        migrations.CreateModel(
            name="VehicleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Дата создания."),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Дата обновления."),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Логическое удаление."
                    ),
                ),
                (
                    "file",
                    sorl.thumbnail.fields.ImageField(
                        help_text="Загрузка изображения для техники.",
                        upload_to="vehicle_images/",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="vehicle.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение техники",
                "verbose_name_plural": "Изображения техники",
            },
        ),
        migrations.AddField(
            model_name="vehicle",
            name="type",
            field=models.ForeignKey(
                help_text="Тип техники.",
                on_delete=django.db.models.deletion.CASCADE,
                to="vehicle.vehicletype",
            ),
        ),
    ]
